"""Blueprint scaffolding and status — ``grd lean init-blueprint`` / ``blueprint-status``.

Generates a leanblueprint-compatible LaTeX skeleton from the GRD phase
task graph and checks formalization status of each node.

Mapping:
  GRD plan entry  →  blueprint ``\\begin{lemma}`` / ``\\begin{theorem}`` node
  plan ``depends_on``  →  ``\\uses{...}`` edge
  Lean typecheck pass  →  ``\\leanok`` marker
  ``\\lean{Module.name}``  →  cross-reference to Lean source file

The dependency graph can be rendered as ASCII (default), SVG (with
graphviz), or JSON for agent consumption.
"""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import BaseModel, Field

__all__ = [
    "BlueprintNode",
    "BlueprintGraph",
    "InitBlueprintResult",
    "BlueprintStatusResult",
    "init_blueprint",
    "blueprint_status",
]


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


class BlueprintNode(BaseModel):
    """One node in the blueprint dependency graph."""

    id: str
    label: str
    kind: str = "lemma"  # lemma | theorem | definition
    lean_name: str | None = None  # e.g. "Proofs.PlanA" — from \lean{...}
    leanok: bool = False
    status: str = "informal"  # informal | stated | proved | failed
    depends_on: list[str] = Field(default_factory=list)
    wave: int = 1
    objective: str | None = None


class BlueprintGraph(BaseModel):
    """Full dependency graph for one phase's blueprint."""

    phase: str
    nodes: list[BlueprintNode] = Field(default_factory=list)
    edges: list[tuple[str, str]] = Field(default_factory=list)  # (from, to)


class InitBlueprintResult(BaseModel):
    """Result of ``grd lean init-blueprint``."""

    ok: bool
    phase: str
    blueprint_dir: str
    files_created: list[str] = Field(default_factory=list)
    node_count: int = 0
    edge_count: int = 0
    error: str | None = None


class BlueprintStatusResult(BaseModel):
    """Result of ``grd lean blueprint-status``."""

    ok: bool
    phase: str
    graph: BlueprintGraph
    summary: dict[str, int] = Field(default_factory=dict)
    ascii_graph: str | None = None
    error: str | None = None


# ---------------------------------------------------------------------------
# init-blueprint
# ---------------------------------------------------------------------------


def _sanitize_id(plan_id: str) -> str:
    """Convert a plan ID like 'analysis-A' to a valid LaTeX label."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", plan_id)


def _lean_module_name(plan_id: str) -> str:
    """Convert a plan ID to a Lean module name: 'analysis-A' -> 'AnalysisA'."""
    parts = re.split(r"[-_ ]+", plan_id)
    return "".join(p.capitalize() for p in parts if p)


def _generate_content_tex(
    nodes: list[BlueprintNode],
    edges: list[tuple[str, str]],
    phase_name: str | None,
    phase_number: str,
    project_name: str | None,
) -> str:
    """Generate the leanblueprint-compatible content.tex."""
    title = phase_name or f"Phase {phase_number}"
    header = textwrap.dedent(f"""\
        % Blueprint for {title}
        % Generated by grd lean init-blueprint
        %
        % Leanblueprint-compatible LaTeX.  Each node maps to a GRD plan entry;
        % \\uses edges mirror the plan dependency graph.  Fill in informal
        % statements, then add \\lean{{Module.Name}} bindings and \\leanok once
        % the Lean proof type-checks.

        \\title{{{title}}}
        \\author{{Generated by Get Research Done}}

        \\begin{{document}}
        \\maketitle
    """)

    body_parts: list[str] = []
    for node in nodes:
        label = _sanitize_id(node.id)
        lean_ref = f"  \\lean{{Proofs.{_lean_module_name(node.id)}}}\n" if node.lean_name else ""
        uses = ""
        deps = [dep for (src, dep) in edges if src == node.id]
        if deps:
            uses = f"  \\uses{{{', '.join(_sanitize_id(d) for d in deps)}}}\n"
        objective_comment = ""
        if node.objective:
            wrapped = textwrap.fill(node.objective, width=76, initial_indent="% ", subsequent_indent="% ")
            objective_comment = f"{wrapped}\n"

        body_parts.append(
            f"{objective_comment}"
            f"\\begin{{{node.kind}}}\\label{{{label}}}\n"
            f"{uses}"
            f"{lean_ref}"
            f"  % TODO: state the informal claim here\n"
            f"\\end{{{node.kind}}}\n"
        )

    footer = "\\end{document}\n"
    return header + "\n".join(body_parts) + "\n" + footer


def _generate_lean_root(nodes: list[BlueprintNode]) -> str:
    """Generate Blueprint.lean that imports all proof modules."""
    lines = [
        "-- Blueprint module root",
        "-- Generated by grd lean init-blueprint",
        "",
    ]
    for node in nodes:
        mod = _lean_module_name(node.id)
        lines.append(f"import Proofs.{mod}")
    lines.append("")
    return "\n".join(lines)


def _generate_lean_stub(plan_id: str) -> str:
    """Generate a stub Lean proof file for one plan entry."""
    mod = _lean_module_name(plan_id)
    return textwrap.dedent(f"""\
        /-
        Proof stub for plan: {plan_id}
        Generated by grd lean init-blueprint — fill in the formal statement
        and proof below, then run `grd lean typecheck-file` to verify.
        -/

        -- TODO: add imports (e.g. import Mathlib.Tactic)

        /-- Formal statement for {plan_id}. Replace `sorry` with a proof. -/
        theorem {mod} : True := by
          sorry
    """)


def _generate_lakefile(phase_name: str | None, phase_number: str) -> str:
    """Generate a minimal lakefile.lean."""
    pkg = f"Blueprint{phase_number.replace('.', '_')}"
    return textwrap.dedent(f"""\
        import Lake
        open Lake DSL

        package «{pkg}» where
          leanOptions := #[
            ⟨`autoImplicit, false⟩
          ]

        @[default_target]
        lean_lib «Proofs» where
          srcDir := "."
    """)


def _generate_lean_toolchain(lean_version: str | None) -> str:
    """Generate lean-toolchain file."""
    version = lean_version or "leanprover/lean4:v4.14.0"
    if not version.startswith("leanprover"):
        version = f"leanprover/lean4:{version}"
    return version + "\n"


def init_blueprint(
    cwd: Path,
    phase: str,
    *,
    force: bool = False,
) -> InitBlueprintResult:
    """Generate a leanblueprint-compatible directory from the phase plan index.

    Creates ``phases/{N}/blueprint/`` with:
      - ``content.tex`` — informal statements + ``\\lean{}`` refs
      - ``lakefile.lean`` — Lake project config
      - ``lean-toolchain`` — toolchain version pin
      - ``Proofs/`` — stub proof files
      - ``Blueprint.lean`` — module root

    Returns an ``InitBlueprintResult`` describing what was created.
    """
    from grd.core.lean.env import load_env  # noqa: PLC0415
    from grd.core.phases import find_phase, phase_plan_index  # noqa: PLC0415
    from grd.core.state import load_state_json  # noqa: PLC0415

    phase_info = find_phase(cwd, phase)
    if phase_info is None:
        return InitBlueprintResult(
            ok=False,
            phase=phase,
            blueprint_dir="",
            error=f"Phase {phase!r} not found. Run `grd phase list` to see available phases.",
        )

    blueprint_dir = cwd / phase_info.directory / "blueprint"
    if blueprint_dir.exists() and not force:
        return InitBlueprintResult(
            ok=False,
            phase=phase_info.phase_number,
            blueprint_dir=str(blueprint_dir.relative_to(cwd)),
            error=f"Blueprint directory already exists: {blueprint_dir.relative_to(cwd)}. Use --force to overwrite.",
        )

    # Build graph from plan index
    plan_idx = phase_plan_index(cwd, phase)
    nodes: list[BlueprintNode] = []
    edges: list[tuple[str, str]] = []

    for plan in plan_idx.plans:
        node = BlueprintNode(
            id=plan.id,
            label=plan.id,
            kind="theorem" if plan.wave == 1 else "lemma",
            wave=plan.wave,
            objective=plan.objective,
            depends_on=list(plan.depends_on),
        )
        nodes.append(node)
        for dep in plan.depends_on:
            edges.append((plan.id, dep))

    # If no plans exist, create a single placeholder node
    if not nodes:
        nodes.append(BlueprintNode(
            id="main",
            label="main",
            kind="theorem",
            objective="Main result (placeholder — add plans to this phase to populate the blueprint)",
        ))

    # Read Lean toolchain version
    lean_env = load_env(cwd)
    lean_version = lean_env.get("lean_version") if lean_env else None

    # Read project name from state
    state = load_state_json(cwd) or {}
    project_name = None
    if isinstance(state.get("project"), dict):
        project_name = state["project"].get("name")

    # Create directory structure
    blueprint_dir.mkdir(parents=True, exist_ok=True)
    proofs_dir = blueprint_dir / "Proofs"
    proofs_dir.mkdir(exist_ok=True)

    files_created: list[str] = []

    # content.tex
    content_tex = _generate_content_tex(
        nodes, edges, phase_info.phase_name, phase_info.phase_number, project_name
    )
    (blueprint_dir / "content.tex").write_text(content_tex, encoding="utf-8")
    files_created.append("content.tex")

    # lakefile.lean
    lakefile = _generate_lakefile(phase_info.phase_name, phase_info.phase_number)
    (blueprint_dir / "lakefile.lean").write_text(lakefile, encoding="utf-8")
    files_created.append("lakefile.lean")

    # lean-toolchain
    toolchain = _generate_lean_toolchain(lean_version)
    (blueprint_dir / "lean-toolchain").write_text(toolchain, encoding="utf-8")
    files_created.append("lean-toolchain")

    # Blueprint.lean (module root)
    root_lean = _generate_lean_root(nodes)
    (blueprint_dir / "Blueprint.lean").write_text(root_lean, encoding="utf-8")
    files_created.append("Blueprint.lean")

    # Proof stubs
    for node in nodes:
        stub = _generate_lean_stub(node.id)
        stub_path = proofs_dir / f"{_lean_module_name(node.id)}.lean"
        stub_path.write_text(stub, encoding="utf-8")
        files_created.append(f"Proofs/{_lean_module_name(node.id)}.lean")

    return InitBlueprintResult(
        ok=True,
        phase=phase_info.phase_number,
        blueprint_dir=str(blueprint_dir.relative_to(cwd)),
        files_created=files_created,
        node_count=len(nodes),
        edge_count=len(edges),
    )


# ---------------------------------------------------------------------------
# blueprint-status
# ---------------------------------------------------------------------------

# Patterns for leanblueprint macros in content.tex
_ENVIRONMENT_RE = re.compile(
    r"\\begin\{(lemma|theorem|definition|proposition|corollary)\}"
    r"\s*\\label\{([^}]+)\}",
    re.DOTALL,
)
_LEAN_REF_RE = re.compile(r"\\lean\{([^}]+)\}")
_LEANOK_RE = re.compile(r"\\leanok\b")
_USES_RE = re.compile(r"\\uses\{([^}]+)\}")
_ENV_END_RE = re.compile(r"\\end\{(lemma|theorem|definition|proposition|corollary)\}")


def _parse_content_tex(content: str) -> tuple[list[BlueprintNode], list[tuple[str, str]]]:
    """Parse content.tex into blueprint nodes and edges."""
    nodes: list[BlueprintNode] = []
    edges: list[tuple[str, str]] = []

    # Split into environments by finding begin/end pairs
    pos = 0
    while pos < len(content):
        env_match = _ENVIRONMENT_RE.search(content, pos)
        if env_match is None:
            break

        kind = env_match.group(1)
        label = env_match.group(2)
        env_start = env_match.end()

        # Find the closing \end{kind}
        end_pattern = re.compile(rf"\\end\{{{re.escape(kind)}\}}")
        end_match = end_pattern.search(content, env_start)
        if end_match is None:
            pos = env_start
            continue

        env_body = content[env_start:end_match.start()]

        # Extract \lean{...}
        lean_match = _LEAN_REF_RE.search(env_body)
        lean_name = lean_match.group(1) if lean_match else None

        # Check for \leanok
        leanok = bool(_LEANOK_RE.search(env_body))

        # Extract \uses{...}
        uses_match = _USES_RE.search(env_body)
        deps: list[str] = []
        if uses_match:
            deps = [d.strip() for d in uses_match.group(1).split(",") if d.strip()]

        # Determine status
        if leanok:
            status = "proved"
        elif lean_name:
            status = "stated"
        else:
            status = "informal"

        node = BlueprintNode(
            id=label,
            label=label,
            kind=kind,
            lean_name=lean_name,
            leanok=leanok,
            status=status,
            depends_on=deps,
        )
        nodes.append(node)
        for dep in deps:
            edges.append((label, dep))

        pos = end_match.end()

    return nodes, edges


def _typecheck_lean_ref(
    lean_name: str,
    blueprint_dir: Path,
    project_root: Path,
) -> bool:
    r"""Check if a ``\lean{...}`` reference typechecks successfully.

    Looks for the corresponding .lean file under Proofs/ and runs
    ``grd lean typecheck-file`` against it.
    """
    # Convert lean module path to file path: Proofs.FooBar -> Proofs/FooBar.lean
    parts = lean_name.split(".")
    relative = Path(*parts).with_suffix(".lean")
    lean_file = blueprint_dir / relative

    if not lean_file.is_file():
        return False

    try:
        from grd.core.lean.client import check_file  # noqa: PLC0415

        result = check_file(
            path=lean_file,
            project_root=project_root,
            timeout_s=60.0,
            use_daemon=True,
            auto_spawn=True,
        )
        return result.ok
    except Exception:
        return False


def _render_ascii_graph(graph: BlueprintGraph) -> str:
    """Render a simple ASCII dependency graph."""
    if not graph.nodes:
        return "(empty blueprint)"

    lines: list[str] = []
    status_symbols = {
        "proved": "[OK]",
        "stated": "[--]",
        "informal": "[  ]",
        "failed": "[!!]",
    }
    color_hints = {
        "proved": "green",
        "stated": "yellow",
        "informal": "grey",
        "failed": "red",
    }

    # Group by wave
    waves: dict[int, list[BlueprintNode]] = {}
    for node in graph.nodes:
        waves.setdefault(node.wave, []).append(node)

    for wave_num in sorted(waves):
        lines.append(f"Wave {wave_num}:")
        for node in waves[wave_num]:
            sym = status_symbols.get(node.status, "[??]")
            deps_str = ""
            if node.depends_on:
                deps_str = f" ← {', '.join(node.depends_on)}"
            lean_str = ""
            if node.lean_name:
                lean_str = f" ({node.lean_name})"
            lines.append(f"  {sym} {node.id}{lean_str}{deps_str}")
        lines.append("")

    # Summary line
    total = len(graph.nodes)
    proved = sum(1 for n in graph.nodes if n.status == "proved")
    stated = sum(1 for n in graph.nodes if n.status == "stated")
    informal = sum(1 for n in graph.nodes if n.status == "informal")
    failed = sum(1 for n in graph.nodes if n.status == "failed")
    lines.append(f"Legend: [OK]=proved  [--]=stated  [  ]=informal  [!!]=failed")
    lines.append(f"Total: {total}  proved: {proved}  stated: {stated}  informal: {informal}  failed: {failed}")

    return "\n".join(lines)


def blueprint_status(
    cwd: Path,
    phase: str,
    *,
    typecheck: bool = True,
) -> BlueprintStatusResult:
    """Walk a phase's blueprint and report formalization status.

    For each ``\\lean{...}`` reference in ``content.tex``, optionally runs
    ``grd lean typecheck-file`` to verify the Lean source compiles, and
    auto-marks nodes whose proofs pass as ``\\leanok``.

    Returns a ``BlueprintStatusResult`` with the full graph, summary counts,
    and an ASCII rendering of the dependency graph.
    """
    from grd.core.phases import find_phase  # noqa: PLC0415

    phase_info = find_phase(cwd, phase)
    if phase_info is None:
        return BlueprintStatusResult(
            ok=False,
            phase=phase,
            graph=BlueprintGraph(phase=phase),
            error=f"Phase {phase!r} not found.",
        )

    blueprint_dir = cwd / phase_info.directory / "blueprint"
    content_tex = blueprint_dir / "content.tex"

    if not content_tex.is_file():
        return BlueprintStatusResult(
            ok=False,
            phase=phase_info.phase_number,
            graph=BlueprintGraph(phase=phase_info.phase_number),
            error=f"No blueprint found. Run `grd lean init-blueprint --phase {phase}` first.",
        )

    content = content_tex.read_text(encoding="utf-8")
    nodes, edges = _parse_content_tex(content)

    # Typecheck each node with a \lean{...} reference
    leanok_updates: list[str] = []
    for node in nodes:
        if node.lean_name and not node.leanok and typecheck:
            ok = _typecheck_lean_ref(node.lean_name, blueprint_dir, cwd)
            if ok:
                node.leanok = True
                node.status = "proved"
                leanok_updates.append(node.id)
            else:
                if node.status == "stated":
                    node.status = "failed"

    # Auto-write \leanok into content.tex for newly passing proofs
    if leanok_updates:
        updated_content = _auto_mark_leanok(content, leanok_updates)
        content_tex.write_text(updated_content, encoding="utf-8")

    graph = BlueprintGraph(phase=phase_info.phase_number, nodes=nodes, edges=edges)

    summary = {
        "total": len(nodes),
        "proved": sum(1 for n in nodes if n.status == "proved"),
        "stated": sum(1 for n in nodes if n.status == "stated"),
        "informal": sum(1 for n in nodes if n.status == "informal"),
        "failed": sum(1 for n in nodes if n.status == "failed"),
        "leanok_updated": len(leanok_updates),
    }

    ascii_graph = _render_ascii_graph(graph)

    return BlueprintStatusResult(
        ok=True,
        phase=phase_info.phase_number,
        graph=graph,
        summary=summary,
        ascii_graph=ascii_graph,
    )


def _auto_mark_leanok(content: str, node_ids: list[str]) -> str:
    """Insert ``\\leanok`` after ``\\lean{...}`` for nodes that now typecheck.

    Only modifies environments whose ``\\label{...}`` matches a node_id in
    the update list. Idempotent — won't double-add if ``\\leanok`` is already
    present.
    """
    ids_remaining = set(node_ids)

    def _replacer(match: re.Match) -> str:
        label_match = re.search(r"\\label\{([^}]+)\}", match.group(0))
        if label_match is None or label_match.group(1) not in ids_remaining:
            return match.group(0)

        body = match.group(0)
        if _LEANOK_RE.search(body):
            return body  # already marked

        # Insert \leanok on the line after \lean{...}
        lean_match = _LEAN_REF_RE.search(body)
        if lean_match:
            insert_pos = lean_match.end()
            body = body[:insert_pos] + "\n  \\leanok" + body[insert_pos:]
        return body

    # Match full environments
    full_env_re = re.compile(
        r"\\begin\{(lemma|theorem|definition|proposition|corollary)\}"
        r".*?"
        r"\\end\{\1\}",
        re.DOTALL,
    )
    return full_env_re.sub(_replacer, content)
